{
 "title": "Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Win Services Status ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Telegraf",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "display_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "startup_mode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "display_name",
       "operator": "=",
       "value": "Telegraf Data Collector Service"
      }
     ]
    }
   ]
  },
  {
   "title": "Influxdb",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "display_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "startup_mode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "display_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "startup_mode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=", "value": "grafana" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Total_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Total/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Received/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Sent/sec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Disk secs/Read and Write",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_diskio",
       "select": [
        [
         { "params": [ "Disk_Reads_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Avg. Disk secs/Read" ], "type": "alias" }
        ],
        [
         { "params": [ "Disk_Writes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Avg. Disk secs/Write" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Queue Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_diskio",
       "select": [
        [
         { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Current Disk Queue Length" ], "type": "alias" }
        ],
        [
         { "params": [ "Avg._Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Avg. Disk Queue Length" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "% Disk Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_diskio",
       "select": [
        [
         { "params": [ "Percent_Disk_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Disk Time" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Processor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processor Queue Length",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_system",
       "query": "SELECT mean(\"Processor_Queue_Length\") AS \"alias\", mean(\"Processor_Queue_Length\") FROM \"win_system\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "Processor_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Processor Queue Length" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Processor",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Processor Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_Idle_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Idle Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Interrupt Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% User Time" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available MBytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "query": "SELECT mean(\"Available_MBytes\") AS \"Available MBytes\", mean(\"Percent_Committed_Bytes_In_Use\") AS \"% Committed Bytes In Use\", mean(\"Page_Faults_persec\") AS \"Pages Faults/sec\", mean(\"Pages_persec\") AS \"Pages/sec\" FROM \"win_mem\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "Available_MBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Available MBytes" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pages Faults/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Page_Faults_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pages Faults/sec" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "% Committed Bytes In Use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "query": "SELECT mean(\"Available_MBytes\") AS \"Available MBytes\", mean(\"Percent_Committed_Bytes_In_Use\") AS \"% Committed Bytes In Use\", mean(\"Page_Faults_persec\") AS \"Pages Faults/sec\", mean(\"Pages_persec\") AS \"Pages/sec\" FROM \"win_mem\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(none)\n",
       "select": [
        [
         { "params": [ "Percent_Committed_Bytes_In_Use" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Committed Bytes In Use" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pages/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Pages_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pages/sec" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}